[1m[34m[*][0m Spooling to file exploits/exploit.36.log...
resource (script.rc)> use auxiliary/admin/cisco/vpn_3000_ftp_bypass
[0m[1m[33m[!][0m 192.168.0.100:21 - *[31m          The module auxiliary/admin/cisco/vpn_3000_ftp_bypass has been moved!          [0m*
[1m[33m[!][0m 192.168.0.100:21 - *           You are using auxiliary/admin/networking/cisco_vpn_3000_ftp_bypass           *
resource (script.rc)> exploit -z
[0m[1m[34m[*][0m Running module against 192.168.0.100
[1m[31m[-][0m 192.168.0.100:21 - Auxiliary failed: Rex::ConnectionRefused The connection was refused by the remote host (192.168.0.100:21).
[1m[31m[-][0m 192.168.0.100:21 - Call stack:
[1m[31m[-][0m 192.168.0.100:21 -   /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/rex-socket-0.1.54/lib/rex/socket/comm/local.rb:309:in `rescue in create_by_type'
[1m[31m[-][0m 192.168.0.100:21 -   /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/rex-socket-0.1.54/lib/rex/socket/comm/local.rb:274:in `create_by_type'
[1m[31m[-][0m 192.168.0.100:21 -   /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/rex-socket-0.1.54/lib/rex/socket/comm/local.rb:36:in `create'
[1m[31m[-][0m 192.168.0.100:21 -   /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/rex-socket-0.1.54/lib/rex/socket.rb:51:in `create_param'
[1m[31m[-][0m 192.168.0.100:21 -   /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/rex-socket-0.1.54/lib/rex/socket/tcp.rb:37:in `create_param'
[1m[31m[-][0m 192.168.0.100:21 -   /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/rex-socket-0.1.54/lib/rex/socket/tcp.rb:28:in `create'
[1m[31m[-][0m 192.168.0.100:21 -   /opt/metasploit-framework/embedded/framework/lib/msf/core/exploit/remote/tcp.rb:102:in `connect'
[1m[31m[-][0m 192.168.0.100:21 -   /opt/metasploit-framework/embedded/framework/modules/auxiliary/admin/networking/cisco_vpn_3000_ftp_bypass.rb:49:in `run'
[1m[34m[*][0m Auxiliary module execution completed
resource (script.rc)> spool off
[0m